server:
  port: 8081


spring:
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
    gateway:
      routes:
        - id: my-service-route
          uri: http://localhost:8084  # 转发地址
          predicates:
            - Path=/api/**  # 所有 /api/** 的请求都会转发
          filters:
            - StripPrefix=1  # 去掉 /api 前缀
            - JwtAuthenticationFilter