server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sleep?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      database: 8
      password: 123456
      port: 6379
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    org.apache.ibatis: ERROR      # 只显示 ERROR 级别日志，不打印 INFO 和 WARN
    com.zaxxer.hikari: ERROR      # 关闭 Hikari 数据库连接池的 INFO 日志

